targets:
  $default:
    builders:
      slang_build_runner:
        options:
          flutter_integration: true
          namespaces: true
          locale_handling: true
          base_locale: en
          fallback_strategy: base_locale
          input_directory: assets/i18n
          input_file_pattern: .i18n.json
          output_directory: lib/i18n
          output_file_name: translations.g.dart
          output_format: single_file
