name: open_bookshelf
description: Digital bookshelf application that utilizes the OpenLibrary API to help users manage their reading lists.
version: 1.0.0

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none"

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Dependency injection
  get_it: ^7.2.0
  # Advanced state management
  provider: ^6.0.5
  # Structured and pretty printing capable logging
  logger: ^2.0.1
  # Communicating with the OpenLibrary API endpoint via HTTP
  http: ^1.1.0
  # Internal bookshelf database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # internationalization (i18n)
  slang: ^3.13.0
  slang_flutter: ^3.13.0
  # Get the device language
  intl: ^0.18.0
  # About page and OpenLibrary links
  url_launcher: ^6.1.10
  # Scanning barcodes for ISBN in books
  mobile_scanner: ^4.0.1
  # Join directories with OS specific separator
  path: ^1.8.3
  # Get device specific storage directories
  path_provider: ^2.0.13
  # Database (json) file picking
  file_picker: ^8.0.1
  # Search bar name matching
  fuzzywuzzy: ^1.1.6
  # Freezed annotations for code generation
  freezed_annotation: ^2.2.0
  # JSON annotations for JSON generation
  json_annotation: ^4.8.0
  # Dynamic theme and layout in devices that support it
  dynamic_color: ^1.6.2
  # Tags color picker
  flutter_colorpicker: ^1.0.3
  # Adaptive scaffold depending on device
  flutter_adaptive_scaffold: ^0.1.7
  # Show the ISBN barcode for the book
  barcode_widget: ^2.0.3
  # Tag expandable region
  expandable: ^5.0.1
  # Share book
  share_plus: ^8.0.3
  # initial splash screen generation
  flutter_native_splash: ^2.2.19
  # QoL flutter extension
  awesome_flutter_extensions: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2
  # Advanced static analysis
  analyzer: ^6.4.1
  # applications icons generation
  flutter_launcher_icons: ^0.13.1
  # Code generation
  build_runner: ^2.4.5
  # Auto-generate translations
  slang_build_runner: ^3.13.0
  # ORM code generation
  hive_generator: ^2.0.0
  # Immutable and value classes
  freezed: ^2.3.5
  # Serialize classes into JSON
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/missing_cover.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

flutter_native_splash:
  color: "#2b1700"
  image: "assets/icons/icon.png"

flutter_launcher_icons:
  android: true
  linux: true

  image_path: "assets/icons/icon.png"
  background_color: "#2b1700"

  adaptive_icon_foreground: "assets/icons/padding.png"
  adaptive_icon_background: "#2b1700"
