name: open_bookshelf
description: Digital bookshelf application that utilizes the OpenLibrary API to help users manage their reading lists.
version: 1.0.0+1
publish_to: "none"

# Use Dart 3.0
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Tools
  logger: ^1.2.2
  http: ^0.13.5
  url_launcher: ^6.1.10
  path_provider: ^2.0.13
  file_picker: ^5.2.10
  mobile_scanner: ^3.2.0
  fuzzywuzzy: ^1.1.6

  # State management
  get_it: ^7.2.0
  provider: ^6.0.5
  shared_preferences: ^2.0.18
  
  # Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Code generation
  slang: ^3.13.0
  slang_flutter: ^3.13.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0

  # Theme and layout
  dynamic_color: ^1.6.2
  flutter_adaptive_scaffold: ^0.1.0
  flutter_colorpicker: ^1.0.3

  # Widgets
  should_rebuild: ^1.0.1
  barcode_widget: ^2.0.3
  expandable: ^5.0.1
  
  # Icons and Splash
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.19
  share_plus: ^7.0.2
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  analyzer: ^5.10.0
  flutter_lints: ^2.0.0
  dart_code_metrics: ^5.7.2

  # Code generation
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  slang_build_runner: ^3.13.0
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/missing_cover.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

flutter_native_splash:
  color: "#2b1700"
  image: "assets/icons/icon.png"

flutter_launcher_icons:

  android: true
  linux: true

  image_path: "assets/icons/icon.png"
  background_color: "#2b1700"
  
  adaptive_icon_foreground: "assets/icons/padding.png"
  adaptive_icon_background: "#2b1700"